#!/usr/bin/env python3
"""Sitewide build step: shared nav + SEO tags, sitemap/robots/404, README table, link check.

    python3 scripts/build.py          # rewrite files in place
    python3 scripts/build.py --check  # CI: fail if anything is stale or a link is broken
"""

import html
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://gopalakrbiec-ui.github.io/FrontierAGI-Academy/"
SITE_NAME = "FrontierAGI Academy"
OG_IMAGE = BASE_URL + "assets/og-default.png"

NAV_START, NAV_END = "<!-- NAV:START (generated by scripts/build.py) -->", "<!-- NAV:END -->"
SERIES_START, SERIES_END = "<!-- SERIES:START (generated by scripts/build.py) -->", "<!-- SERIES:END -->"
SEO_START, SEO_END = "<!-- SEO:START (generated by scripts/build.py) -->", "<!-- SEO:END -->"

ECOSYSTEM_PAGES = {"usa-ai", "china-ai", "india-ai", "europe-ai", "sovereign-ai"}


def html_files():
    files = [ROOT / "index.html"]
    files += sorted((ROOT / "pages").glob("*.html"))
    files += sorted((ROOT / "blog").glob("*.html"))
    return files


def prefixes(path):
    folder = path.parent.name if path.parent != ROOT else ""
    if folder == "pages":
        return {"ROOT": "../", "PAGES": "", "BLOG": "../blog/"}
    if folder == "blog":
        return {"ROOT": "../", "PAGES": "../pages/", "BLOG": ""}
    return {"ROOT": "", "PAGES": "pages/", "BLOG": "blog/"}


def active_tab(path):
    folder, stem = path.parent.name, path.stem
    if folder == "blog" or stem == "blog":
        return "blog"
    if stem == "ai-news":
        return "news"
    if stem in ECOSYSTEM_PAGES:
        return "ecosystems"
    if stem == "frontier-model-learning":
        return "mode"
    if folder == "pages":
        return "explore"
    return None


def render_nav(template, path):
    out = template
    for key, val in prefixes(path).items():
        out = out.replace("{{%s}}" % key, val)
    active = active_tab(path)
    for tab in ("mode", "explore", "ecosystems", "blog", "news"):
        out = out.replace("{{ACTIVE_%s}}" % tab, " active" if tab == active else "")
    return f"{NAV_START}\n{out.rstrip()}\n{NAV_END}"


def div_block_end(s, start):
    depth = 0
    for m in re.finditer(r"<div\b|</div>", s[start:]):
        depth += 1 if m.group(0) == "<div" else -1
        if depth == 0:
            return start + m.end()
    raise ValueError("unbalanced div")


def replace_nav(s, block, path):
    if NAV_START in s:
        a, b = s.index(NAV_START), s.index(NAV_END) + len(NAV_END)
        return s[:a] + block + s[b:]
    a = s.find('<nav class="navbar"')
    w = s.find('<div class="nav-panel-wrap"', a)
    if a < 0 or w < 0:
        raise ValueError(f"{path}: navbar or nav-panel-wrap not found")
    return s[:a] + block + s[div_block_end(s, w):]


def clean_text(fragment):
    text = html.unescape(re.sub(r"<[^>]+>", "", fragment))
    return re.sub(r"\s+", " ", text).strip()


def truncate(text, limit=160):
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0].rstrip(",;:—-") + "…"


def page_description(s):
    after_nav = s[s.find(NAV_END):] if NAV_END in s else s
    for p in re.findall(r"<p[^>]*>(.*?)</p>", after_nav, re.S):
        text = clean_text(p)
        if len(text) > 70:
            return text
    return f"{SITE_NAME} — tracking the path to AGI."


def render_seo(path, s, manifest):
    rel = path.relative_to(ROOT).as_posix()
    url = BASE_URL + ("" if rel == "index.html" else rel)
    title = clean_text(re.search(r"<title>(.*?)</title>", s, re.S).group(1))
    post = manifest.get(path.stem) if path.parent.name == "blog" else None
    if post:
        desc, og_type, og_title = post["excerpt"], "article", post["title"]
    else:
        desc, og_type, og_title = page_description(s), "website", title
    desc = html.escape(truncate(clean_text(desc)), quote=True)
    og_title = html.escape(og_title, quote=True)
    lines = [
        SEO_START,
        f'  <meta name="description" content="{desc}" />',
        f'  <link rel="canonical" href="{url}" />',
        f'  <meta property="og:site_name" content="{SITE_NAME}" />',
        f'  <meta property="og:type" content="{og_type}" />',
        f'  <meta property="og:title" content="{og_title}" />',
        f'  <meta property="og:description" content="{desc}" />',
        f'  <meta property="og:url" content="{url}" />',
        f'  <meta property="og:image" content="{OG_IMAGE}" />',
        '  <meta name="twitter:card" content="summary_large_image" />',
    ]
    if post:
        lines.append(f'  <meta property="article:published_time" content="{post["date"]}" />')
    lines.append(f"  {SEO_END}")
    return "\n".join(lines)


def replace_seo(s, block):
    return re.sub(r"[ \t]*" + re.escape(SEO_START), "  " + SEO_START, _replace_seo(s, block), count=1)


def _replace_seo(s, block):
    if SEO_START in s:
        a, b = s.index(SEO_START), s.index(SEO_END) + len(SEO_END)
        return s[:a] + block.lstrip() + s[b:]
    m = re.search(r"</title>\s*", s)
    return s[: m.end()] + "  " + block + "\n  " + s[m.end():].lstrip(" ")


def render_sitemap(files, manifest):
    rows = []
    for f in files:
        if f.name.startswith("_"):
            continue
        rel = f.relative_to(ROOT).as_posix()
        post = manifest.get(f.stem) if f.parent.name == "blog" else None
        lastmod = post["date"] if post else date.today().isoformat()
        loc = BASE_URL + ("" if rel == "index.html" else rel)
        rows.append(f"  <url><loc>{loc}</loc><lastmod>{lastmod}</lastmod></url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(rows) + "\n</urlset>\n")


ROBOTS = f"User-agent: *\nAllow: /\n\nSitemap: {BASE_URL}sitemap.xml\n"


def render_404(nav_template):
    base = "/FrontierAGI-Academy/"
    nav = nav_template
    for key, val in {"ROOT": base, "PAGES": base + "pages/", "BLOG": base + "blog/"}.items():
        nav = nav.replace("{{%s}}" % key, val)
    nav = re.sub(r"\{\{ACTIVE_\w+\}\}", "", nav)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex" />
  <title>Page Not Found — {SITE_NAME}</title>
  <link rel="icon" type="image/svg+xml" href="{base}assets/favicon.svg" />
  <link rel="stylesheet" href="{base}styles.css" />
</head>
<body>
{nav.rstrip()}
<main style="padding-top: 94px;">
  <div class="container" style="max-width: 640px; margin: 80px auto; text-align: center; padding: 0 16px;">
    <div style="font-size: 3.5rem;">🧭</div>
    <h1 style="margin: 12px 0;">This page doesn't exist</h1>
    <p style="color: #6b7280;">The link may be outdated, or the article may have been renamed.</p>
    <p style="margin-top: 24px;">
      <a href="{base}index.html">Go to the homepage</a> ·
      <a href="{base}pages/blog.html">Browse all articles</a>
    </p>
  </div>
</main>
<script src="{base}app.js"></script>
</body>
</html>
"""


ICON_OVERRIDES = {"sec-rsi": "🔁", "sec-lineage": "🗂️"}
PRIMARY_SERIES = {"sec-rsi"}


def spotlight_blocks(index_html):
    pattern = r'<div class="home-(?:series|rsi|lineage)-spotlight[^"]*" id="(sec-[^"]+)"'
    for m in re.finditer(pattern, index_html):
        yield m.group(1), m.start(), div_block_end(index_html, m.start())


def load_series(index_html):
    """Series = each homepage spotlight grid, in card order. A post listed twice keeps its first series."""
    series, owner = [], {}
    for sec_id, a, b in spotlight_blocks(index_html):
        block = index_html[a:b]
        title = re.search(r'class="home-(?:series|rsi|lineage)-title"[^>]*>(.*?)</div>', block, re.S)
        tag = re.search(r'class="home-(?:series|rsi|lineage)-tag">\s*(\S+)', block)
        slugs = list(dict.fromkeys(re.findall(r'href="blog/([^"#]+)\.html"', block)))
        full = clean_text(title.group(1)) if title else sec_id
        entry = {
            "id": sec_id,
            "title": full,
            "short": full.split(":")[0].strip(),
            "icon": ICON_OVERRIDES.get(sec_id, tag.group(1) if tag else "📚"),
            "slugs": slugs,
        }
        series.append(entry)
    # A post listed in two spotlights belongs to the first one in page order, except that a
    # PRIMARY_SERIES spotlight always keeps its own posts (so moving sections doesn't re-home them).
    for entry in sorted(series, key=lambda e: e["id"] not in PRIMARY_SERIES):
        for slug in entry["slugs"]:
            owner.setdefault(slug, entry)
    return series, owner


def sync_series_counts(index_html):
    """Keep the hand-written "· N Articles" labels on homepage spotlights equal to the real card count."""
    out, last = [], 0
    for _, a, b in spotlight_blocks(index_html):
        block = index_html[a:b]
        n = len(set(re.findall(r'href="blog/([^"#]+)\.html"', block)))
        block = re.sub(r'(home-series-tag">[^<]*?· )\d+ Articles?',
                       lambda m: f"{m.group(1)}{n} Article{'s' if n != 1 else ''}", block, count=1)
        out.append(index_html[last:a] + block)
        last = b
    return "".join(out) + index_html[last:]


def render_series(slug, owner, manifest):
    entry = owner.get(slug)
    if not entry or len(entry["slugs"]) < 2:
        return ""
    slugs = entry["slugs"]
    i = slugs.index(slug)

    def link(cls, label, target):
        if target is None:
            return f'<span class="{cls} is-empty"></span>'
        title = html.escape(manifest[target]["title"])
        return (f'<a class="{cls}" href="{target}.html"><span>{label}</span>'
                f'<strong>{title}</strong></a>')

    prev_slug = slugs[i - 1] if i > 0 else None
    next_slug = slugs[i + 1] if i + 1 < len(slugs) else None
    return "\n".join([
        SERIES_START,
        '<nav class="series-footer" aria-label="Series navigation">',
        f'  <div class="series-footer-label">Part of <a href="../index.html#{entry["id"]}">'
        f'{html.escape(entry["title"])}</a> · {i + 1} of {len(slugs)}</div>',
        '  <div class="series-footer-links">',
        "    " + link("series-prev", "← Previous", prev_slug),
        "    " + link("series-next", "Next →", next_slug),
        "  </div>",
        "</nav>",
        SERIES_END,
    ])


def replace_series(s, block):
    if SERIES_START in s:
        a, b = s.index(SERIES_START), s.index(SERIES_END) + len(SERIES_END)
        s = (s[:a].rstrip("\n") + "\n" + s[b:].lstrip("\n")) if not block else s[:a] + block + s[b:]
        return s
    if not block:
        return s
    i = s.rindex("</main>")
    return s[:i] + block + "\n" + s[i:]


def broken_links(files):
    ids = {f: set(re.findall(r'id="([^"]+)"', f.read_text(encoding="utf-8"))) for f in files}
    problems = []
    for f in files:
        for href in re.findall(r'(?:href|src)="([^"]+)"', f.read_text(encoding="utf-8")):
            if href.startswith(("http:", "https:", "mailto:", "javascript:", "data:")) or "${" in href:
                continue
            target_path, _, frag = href.partition("#")
            target_path = target_path.split("?")[0]
            target = f if not target_path else (f.parent / target_path).resolve()
            if not target.exists():
                problems.append(f"{f.relative_to(ROOT)}: missing file {href}")
            elif frag and target in ids and frag not in ids[target]:
                problems.append(f"{f.relative_to(ROOT)}: missing anchor {href}")
    return problems


LABSTRIP_START, LABSTRIP_END = "<!-- LABSTRIP:START (generated by scripts/build.py) -->", "<!-- LABSTRIP:END -->"
LABLATEST_START, LABLATEST_END = "<!-- LABLATEST:START (generated by scripts/build.py) -->", "<!-- LABLATEST:END -->"


def load_lab_updates():
    """data/lab-updates.json → (data, problems). Items sorted newest first."""
    data = json.loads((ROOT / "data/lab-updates.json").read_text(encoding="utf-8"))
    labs, types = {l[0] for l in data["labs"]}, {t[0] for t in data["types"]}
    lo, hi = data["range"]
    problems, seen = [], set()
    for it in data["items"]:
        where = f"data/lab-updates.json: {it.get('id', '?')}"
        if not re.fullmatch(r"20\d\d-\d\d(-\d\d)?", it["date"]):
            problems.append(f"{where}: bad date {it['date']}")
        elif not lo[:len(it["date"])] <= it["date"] <= hi[:len(it["date"])]:
            problems.append(f"{where}: date {it['date']} outside {lo}..{hi}")
        if it["lab"] not in labs:
            problems.append(f"{where}: unknown lab {it['lab']}")
        if it["type"] not in types:
            problems.append(f"{where}: unknown type {it['type']}")
        if not it.get("source", "").startswith("https://"):
            problems.append(f"{where}: source must be an https:// link")
        if not it.get("title") or not it.get("summary"):
            problems.append(f"{where}: title and summary are required")
        if it["id"] in seen:
            problems.append(f"{where}: duplicate id")
        seen.add(it["id"])
    data["items"].sort(key=lambda x: (x["date"], x["lab"]), reverse=True)
    return data, problems


def fmt_lab_date(d):
    y, m, *rest = d.split("-")
    mon = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][int(m) - 1]
    return f"{int(rest[0])} {mon} {y}" if rest else f"{mon} {y}"


def render_lab_blocks(data):
    """Homepage ticker strip (latest 12) and 'Latest from the Labs' section (latest 6)."""
    labs = {l[0]: l for l in data["labs"]}
    icon = {t[0]: t[1] for t in data["types"]}
    e = lambda s: html.escape(s, quote=True)
    ticks = "".join(
        f'<a href="pages/lab-updates.html#{e(it["id"])}" class="labstrip-item"><b style="--lc:{labs[it["lab"]][3]}">{e(labs[it["lab"]][1])}</b>'
        f'{icon[it["type"]]} {e(it["title"])} <time datetime="{it["date"]}">{fmt_lab_date(it["date"])}</time></a>'
        for it in data["items"][:12])
    dup = ticks.replace("<a ", '<a aria-hidden="true" tabindex="-1" ')
    strip = (f'{LABSTRIP_START}\n  <div class="labstrip" aria-label="Latest announcements from frontier AI labs">'
             f'<a href="pages/lab-updates.html" class="labstrip-hd">🆕 Latest from the labs</a>'
             f'<div class="labstrip-viewport"><div class="labstrip-track">{ticks}{dup}</div></div></div>\n  {LABSTRIP_END}')
    cards = "".join(
        f'\n        <a href="pages/lab-updates.html#{e(it["id"])}" class="lablatest-card" style="--lc:{labs[it["lab"]][3]}">'
        f'<span class="lablatest-top"><i>{e(labs[it["lab"]][2])}</i>{e(labs[it["lab"]][1])} · {icon[it["type"]]}</span>'
        f'<strong>{e(it["title"])}</strong><span class="lablatest-sum">{e(it["summary"])}</span>'
        f'<time datetime="{it["date"]}">{fmt_lab_date(it["date"])}</time></a>'
        for it in data["items"][:6])
    latest = (f'{LABLATEST_START}\n<div class="home-section lablatest" id="grp-labs">\n  <div class="container">\n'
              f'    <div class="home-section-hd">\n      <div class="eyebrow">Frontier Lab Updates</div>\n'
              f'      <h2>Latest from the Labs</h2>\n      <p>Every release and announcement from {len(labs)} frontier labs over the last five years — models, products, APIs, pricing and research — newest first, each linked to its source.</p>\n    </div>\n'
              f'    <div class="lablatest-grid">{cards}\n    </div>\n'
              f'    <a href="pages/lab-updates.html" class="lablatest-all">See all {len(data["items"])} updates, filter by lab →</a>\n  </div>\n</div>\n{LABLATEST_END}')
    return strip, latest


LABITEMS_START, LABITEMS_END = "<!-- LABITEMS:START (generated by scripts/build.py) -->", "<!-- LABITEMS:END -->"


def render_lab_items(data):
    """Static timeline for pages/lab-updates.html: month groups of cards, newest first (JS adds filters)."""
    labs = {l[0]: l for l in data["labs"]}
    types = {t[0]: t for t in data["types"]}
    e = lambda s: html.escape(s, quote=True)
    out, month = [LABITEMS_START], None
    for it in data["items"]:
        m = it["date"][:7]
        if m != month:
            if month:
                out.append("    </div></section>")
            out.append(f'    <section class="lu-month" data-month="{m}"><h3 class="lu-month-hd">{fmt_lab_date(m)}</h3><div class="lu-cards">')
            month = m
        lab, typ = labs[it["lab"]], types[it["type"]]
        facts = "".join(f"<li>{e(f)}</li>" for f in it["facts"])
        flag_cls = " is-flag" if it["flagship"] else ""
        flag_pill = '<span class="lu-flag">⭐ Flagship</span>' if it["flagship"] else ""
        facts_ul = f'<ul class="lu-facts">{facts}</ul>' if facts else ""
        out.append(
            f'      <article class="lu-card{flag_cls}" id="{e(it["id"])}" data-lab="{it["lab"]}" data-type="{it["type"]}" data-date="{it["date"]}" data-flag="{int(it["flagship"])}" style="--lc:{lab[3]}">'
            f'<div class="lu-art" aria-hidden="true"><span class="lu-mono">{e(lab[2])}</span><span class="lu-ticon">{typ[1]}</span></div>'
            f'<div class="lu-body"><div class="lu-meta"><span class="lu-lab">{e(lab[1])}</span><span class="lu-type">{typ[1]} {e(typ[2])}</span>'
            f'{flag_pill}<time datetime="{it["date"]}">{fmt_lab_date(it["date"])}</time></div>'
            f'<h4>{e(it["title"])}</h4><p>{e(it["summary"])}</p>'
            f'{facts_ul}'
            f'<a class="lu-src" href="{e(it["source"])}" target="_blank" rel="noopener">Source ↗</a></div></article>')
    if month:
        out.append("    </div></section>")
    out.append("    " + LABITEMS_END)
    return "\n".join(out)


def replace_block(s, start, end, block):
    if start not in s:
        return s
    a, b = s.index(start), s.index(end) + len(end)
    return s[:a] + block + s[b:]


PRIZE_WORDS = ("Nobel", "Turing", "Gödel", "Test of Time", "Best Paper", "Outstanding", "Award", "Prize")


def validate_rsi():
    """data/rsi-papers.json (generated by scripts/import_awesome_rsi.py): structural checks for pages/rsi-evolution.html."""
    path = ROOT / "data/rsi-papers.json"
    if not path.exists():
        return []
    d = json.loads(path.read_text(encoding="utf-8"))
    fams, lvls = {f[0] for f in d["families"]}, {l[0] for l in d["levels"]}
    problems, seen = [], set()
    for k in ("name", "repo", "survey", "license"):
        if not d.get("source", {}).get(k):
            problems.append(f"data/rsi-papers.json: source.{k} is required (attribution)")
    for p in d["papers"]:
        w = f"data/rsi-papers.json: paper {p.get('id', '?')}"
        if not re.fullmatch(r"\d{4}\.\d{4,5}", p["id"]):
            problems.append(f"{w}: bad arXiv id")
        if p["d"] != "20" + p["id"][:2] + "-" + p["id"][2:4]:
            problems.append(f"{w}: date {p['d']} does not match its arXiv id")
        if p["l"] not in lvls:
            problems.append(f"{w}: unknown level {p['l']}")
        if p["f"] not in fams or any(c not in fams for c in p["o"]) or p["f"] not in p["o"]:
            problems.append(f"{w}: unknown family, or primary family missing from o")
        if p["id"] in seen:
            problems.append(f"{w}: duplicate")
        seen.add(p["id"])
    for i in d["industry"]:
        w = f"data/rsi-papers.json: industry {i.get('org', '?')} {i.get('date', '?')}"
        if not re.fullmatch(r"20\d\d-\d\d(-\d\d)?", i["date"]) or not i["url"].startswith("https://") or not i["result"]:
            problems.append(f"{w}: needs a valid date, an https url and a result")
    return problems


def render_idea_graph():
    """Merge data/idea-map.json (areas, lineage links, tours) with every paper card in the
    "AI Research in YEAR" articles into blog/idea-graph.json for pages/idea-map.html.
    Returns (json_text, problems)."""
    src = json.loads((ROOT / "data/idea-map.json").read_text(encoding="utf-8"))
    labels = src.get("labels", {})
    nodes, problems = [], []
    for f in sorted((ROOT / "blog").glob("ai-research-*-papers.html")):
        s = f.read_text(encoding="utf-8")
        span = f.stem[len("ai-research-"):-len("-papers")]
        years = [int(y) for y in span.split("-")]
        short = {p[0]: p for p in json.loads(re.search(r"const P = (\[\[.*?\]\]);", s).group(1))}
        legend = dict(re.findall(r'<span class="ar-b ([\w-]+)">([^<]+)</span>', s[s.find('class="ar-legend"'):][:3000]))
        for m in re.finditer(r'<div class="ar-card" id="([^"]+)">(.*?)<div class="op-refs">', s, re.S):
            cid, card = m.groups()
            key = f"{span}/{cid}"
            small = clean_text(re.search(r"<small>(.*?)</small>", card, re.S).group(1))
            year = years[0]
            if len(years) > 1:
                found = [int(y) for y in re.findall(r"\b(19\d\d|20\d\d)\b", small) if years[0] <= int(y) <= years[1]]
                year = found[0] if found else years[0]
            eli = re.search(r'<div class="ar-eli"><b>[^<]*</b><p>(.*?)</p>', card, re.S)
            desc = clean_text(eli.group(1)) if eli else ""
            first = re.match(r"(.+?[.!?])(\s|$)", desc)
            badges = [html.unescape(legend.get(b, b)) for b in short.get(cid, [0] * 5)[4]]
            nodes.append({
                "id": key, "y": year, "a": src["nodeArea"].get(key, ""),
                "t": labels.get(key) or html.unescape(short[cid][3]) if cid in short else cid,
                "e": short[cid][2] if cid in short else "•",
                "d": truncate(first.group(1) if first else desc, 190),
                "w": small, "b": badges, "p": any(w in b for b in badges for w in PRIZE_WORDS),
                "u": f"../blog/{f.name}#{cid}", "l": f"AI Research in {span.replace('-', '–')}",
            })
    keys = {n["id"] for n in nodes}
    area_ids = {a[0] for a in src["areas"]}
    problems += [f"data/idea-map.json: card {k} has no area" for k in sorted(keys) if src["nodeArea"].get(k) not in area_ids]
    problems += [f"data/idea-map.json: unknown card {k} in nodeArea" for k in src["nodeArea"] if k not in keys]
    problems += [f"data/idea-map.json: link to unknown card {x}" for l in src["links"] for x in l[:2] if x not in keys]
    problems += [f"data/idea-map.json: tour stop {x} unknown" for t in src["tours"] for x in t[1] if x not in keys]
    problems += [f"data/idea-map.json: core idea {x} unknown" for x in src.get("core", []) if x not in keys]
    out = {"generated_by": "scripts/build.py from data/idea-map.json + blog/ai-research-*-papers.html",
           "areas": src["areas"], "nodes": nodes, "links": src["links"], "tours": src["tours"], "core": src.get("core", [])}
    return json.dumps(out, ensure_ascii=False, separators=(",", ":")) + "\n", problems


def main():
    check = "--check" in sys.argv
    manifest = {p["slug"]: p for p in json.loads((ROOT / "blog/index.json").read_text())["posts"]}
    nav_template = (ROOT / "partials/nav.html").read_text(encoding="utf-8")
    files = html_files()
    series, series_owner = load_series((ROOT / "index.html").read_text(encoding="utf-8"))

    lab_data, lab_problems = load_lab_updates()
    lab_strip, lab_latest = render_lab_blocks(lab_data)
    lab_items = render_lab_items(lab_data)
    outputs = {}
    for f in files:
        s = f.read_text(encoding="utf-8")
        s = replace_nav(s, render_nav(nav_template, f), f)
        s = replace_seo(s, render_seo(f, s, manifest))
        if f.name == "index.html" and f.parent == ROOT:
            s = sync_series_counts(s)
            s = replace_block(s, LABSTRIP_START, LABSTRIP_END, lab_strip)
            s = replace_block(s, LABLATEST_START, LABLATEST_END, lab_latest)
        if f.name == "lab-updates.html" and f.parent.name == "pages":
            s = replace_block(s, LABITEMS_START, LABITEMS_END, lab_items)
        if f.parent.name == "blog" and f.stem in manifest:
            s = replace_series(s, render_series(f.stem, series_owner, manifest))
        outputs[f] = s
    outputs[ROOT / "blog/series.json"] = json.dumps(
        {"generated_by": "scripts/build.py", "series": series}, indent=2, ensure_ascii=False) + "\n"
    outputs[ROOT / "blog/idea-graph.json"], graph_problems = render_idea_graph()
    outputs[ROOT / "sitemap.xml"] = render_sitemap(files, manifest)
    outputs[ROOT / "robots.txt"] = ROBOTS
    outputs[ROOT / "404.html"] = render_404(nav_template)

    stale = [p for p, s in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != s]
    if check:
        # sitemap lastmod for non-post pages uses today's date, so ignore date-only drift there
        stale = [p for p in stale if p.name != "sitemap.xml"]
        readme = subprocess.run([sys.executable, str(ROOT / "scripts/update_readme.py"), "--check"])
        problems = [f"stale: {p.relative_to(ROOT)} (run python3 scripts/build.py)" for p in stale]
        problems += broken_links(files) + graph_problems + lab_problems + validate_rsi()
        if readme.returncode:
            problems.append("stale: README.md (run python3 scripts/build.py)")
        for line in problems:
            print(line)
        sys.exit(1 if problems else 0)

    for p in stale:
        p.write_text(outputs[p], encoding="utf-8")
    subprocess.run([sys.executable, str(ROOT / "scripts/update_readme.py")], check=True)
    problems = broken_links(files) + graph_problems + lab_problems + validate_rsi()
    print(f"build: {len(stale)} file(s) updated, {len(files)} pages checked, {len(problems)} broken link(s)")
    for line in problems:
        print("  " + line)
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
