#!/usr/bin/env python3
"""Sitewide build step: shared nav + SEO tags, sitemap/robots/404, README table, link check.

    python3 scripts/build.py          # rewrite files in place
    python3 scripts/build.py --check  # CI: fail if anything is stale or a link is broken
"""

import html
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://gopalakrbiec-ui.github.io/FrontierAGI-Academy/"
SITE_NAME = "FrontierAGI Academy"
OG_IMAGE = BASE_URL + "assets/og-default.png"

NAV_START, NAV_END = "<!-- NAV:START (generated by scripts/build.py) -->", "<!-- NAV:END -->"
SERIES_START, SERIES_END = "<!-- SERIES:START (generated by scripts/build.py) -->", "<!-- SERIES:END -->"
SEO_START, SEO_END = "<!-- SEO:START (generated by scripts/build.py) -->", "<!-- SEO:END -->"

ECOSYSTEM_PAGES = {"usa-ai", "china-ai", "india-ai", "europe-ai", "sovereign-ai"}


def html_files():
    files = [ROOT / "index.html"]
    files += sorted((ROOT / "pages").glob("*.html"))
    files += sorted((ROOT / "blog").glob("*.html"))
    return files


def prefixes(path):
    folder = path.parent.name if path.parent != ROOT else ""
    if folder == "pages":
        return {"ROOT": "../", "PAGES": "", "BLOG": "../blog/"}
    if folder == "blog":
        return {"ROOT": "../", "PAGES": "../pages/", "BLOG": ""}
    return {"ROOT": "", "PAGES": "pages/", "BLOG": "blog/"}


def active_tab(path):
    folder, stem = path.parent.name, path.stem
    if folder == "blog" or stem == "blog":
        return "blog"
    if stem == "ai-news":
        return "news"
    if stem in ECOSYSTEM_PAGES:
        return "ecosystems"
    if stem == "frontier-model-learning":
        return "mode"
    if folder == "pages":
        return "explore"
    return None


def render_nav(template, path):
    out = template
    for key, val in prefixes(path).items():
        out = out.replace("{{%s}}" % key, val)
    active = active_tab(path)
    for tab in ("mode", "explore", "ecosystems", "blog", "news"):
        out = out.replace("{{ACTIVE_%s}}" % tab, " active" if tab == active else "")
    return f"{NAV_START}\n{out.rstrip()}\n{NAV_END}"


def div_block_end(s, start):
    depth = 0
    for m in re.finditer(r"<div\b|</div>", s[start:]):
        depth += 1 if m.group(0) == "<div" else -1
        if depth == 0:
            return start + m.end()
    raise ValueError("unbalanced div")


def replace_nav(s, block, path):
    if NAV_START in s:
        a, b = s.index(NAV_START), s.index(NAV_END) + len(NAV_END)
        return s[:a] + block + s[b:]
    a = s.find('<nav class="navbar"')
    w = s.find('<div class="nav-panel-wrap"', a)
    if a < 0 or w < 0:
        raise ValueError(f"{path}: navbar or nav-panel-wrap not found")
    return s[:a] + block + s[div_block_end(s, w):]


def clean_text(fragment):
    text = html.unescape(re.sub(r"<[^>]+>", "", fragment))
    return re.sub(r"\s+", " ", text).strip()


def truncate(text, limit=160):
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0].rstrip(",;:—-") + "…"


def page_description(s):
    after_nav = s[s.find(NAV_END):] if NAV_END in s else s
    for p in re.findall(r"<p[^>]*>(.*?)</p>", after_nav, re.S):
        text = clean_text(p)
        if len(text) > 70:
            return text
    return f"{SITE_NAME} — tracking the path to AGI."


def render_seo(path, s, manifest):
    rel = path.relative_to(ROOT).as_posix()
    url = BASE_URL + ("" if rel == "index.html" else rel)
    title = clean_text(re.search(r"<title>(.*?)</title>", s, re.S).group(1))
    post = manifest.get(path.stem) if path.parent.name == "blog" else None
    if post:
        desc, og_type, og_title = post["excerpt"], "article", post["title"]
    else:
        desc, og_type, og_title = page_description(s), "website", title
    desc = html.escape(truncate(clean_text(desc)), quote=True)
    og_title = html.escape(og_title, quote=True)
    lines = [
        SEO_START,
        f'  <meta name="description" content="{desc}" />',
        f'  <link rel="canonical" href="{url}" />',
        f'  <meta property="og:site_name" content="{SITE_NAME}" />',
        f'  <meta property="og:type" content="{og_type}" />',
        f'  <meta property="og:title" content="{og_title}" />',
        f'  <meta property="og:description" content="{desc}" />',
        f'  <meta property="og:url" content="{url}" />',
        f'  <meta property="og:image" content="{OG_IMAGE}" />',
        '  <meta name="twitter:card" content="summary_large_image" />',
    ]
    if post:
        lines.append(f'  <meta property="article:published_time" content="{post["date"]}" />')
    lines.append(f"  {SEO_END}")
    return "\n".join(lines)


def replace_seo(s, block):
    return re.sub(r"[ \t]*" + re.escape(SEO_START), "  " + SEO_START, _replace_seo(s, block), count=1)


def _replace_seo(s, block):
    if SEO_START in s:
        a, b = s.index(SEO_START), s.index(SEO_END) + len(SEO_END)
        return s[:a] + block.lstrip() + s[b:]
    m = re.search(r"</title>\s*", s)
    return s[: m.end()] + "  " + block + "\n  " + s[m.end():].lstrip(" ")


def render_sitemap(files, manifest):
    rows = []
    for f in files:
        if f.name.startswith("_"):
            continue
        rel = f.relative_to(ROOT).as_posix()
        post = manifest.get(f.stem) if f.parent.name == "blog" else None
        lastmod = post["date"] if post else date.today().isoformat()
        loc = BASE_URL + ("" if rel == "index.html" else rel)
        rows.append(f"  <url><loc>{loc}</loc><lastmod>{lastmod}</lastmod></url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(rows) + "\n</urlset>\n")


ROBOTS = f"User-agent: *\nAllow: /\n\nSitemap: {BASE_URL}sitemap.xml\n"


def render_404(nav_template):
    base = "/FrontierAGI-Academy/"
    nav = nav_template
    for key, val in {"ROOT": base, "PAGES": base + "pages/", "BLOG": base + "blog/"}.items():
        nav = nav.replace("{{%s}}" % key, val)
    nav = re.sub(r"\{\{ACTIVE_\w+\}\}", "", nav)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex" />
  <title>Page Not Found — {SITE_NAME}</title>
  <link rel="icon" type="image/svg+xml" href="{base}assets/favicon.svg" />
  <link rel="stylesheet" href="{base}styles.css" />
</head>
<body>
{nav.rstrip()}
<main style="padding-top: 94px;">
  <div class="container" style="max-width: 640px; margin: 80px auto; text-align: center; padding: 0 16px;">
    <div style="font-size: 3.5rem;">🧭</div>
    <h1 style="margin: 12px 0;">This page doesn't exist</h1>
    <p style="color: #6b7280;">The link may be outdated, or the article may have been renamed.</p>
    <p style="margin-top: 24px;">
      <a href="{base}index.html">Go to the homepage</a> ·
      <a href="{base}pages/blog.html">Browse all articles</a>
    </p>
  </div>
</main>
<script src="{base}app.js"></script>
</body>
</html>
"""


ICON_OVERRIDES = {"sec-rsi": "🔁", "sec-lineage": "🗂️"}


def spotlight_blocks(index_html):
    pattern = r'<div class="home-(?:series|rsi|lineage)-spotlight[^"]*" id="(sec-[^"]+)"'
    for m in re.finditer(pattern, index_html):
        yield m.group(1), m.start(), div_block_end(index_html, m.start())


def load_series(index_html):
    """Series = each homepage spotlight grid, in card order. A post listed twice keeps its first series."""
    series, owner = [], {}
    for sec_id, a, b in spotlight_blocks(index_html):
        block = index_html[a:b]
        title = re.search(r'class="home-(?:series|rsi|lineage)-title"[^>]*>(.*?)</div>', block, re.S)
        tag = re.search(r'class="home-(?:series|rsi|lineage)-tag">\s*(\S+)', block)
        slugs = list(dict.fromkeys(re.findall(r'href="blog/([^"#]+)\.html"', block)))
        full = clean_text(title.group(1)) if title else sec_id
        entry = {
            "id": sec_id,
            "title": full,
            "short": full.split(":")[0].strip(),
            "icon": ICON_OVERRIDES.get(sec_id, tag.group(1) if tag else "📚"),
            "slugs": slugs,
        }
        series.append(entry)
        for slug in slugs:
            owner.setdefault(slug, entry)
    return series, owner


def sync_series_counts(index_html):
    """Keep the hand-written "· N Articles" labels on homepage spotlights equal to the real card count."""
    out, last = [], 0
    for _, a, b in spotlight_blocks(index_html):
        block = index_html[a:b]
        n = len(set(re.findall(r'href="blog/([^"#]+)\.html"', block)))
        block = re.sub(r'(home-series-tag">[^<]*?· )\d+ Articles?',
                       lambda m: f"{m.group(1)}{n} Article{'s' if n != 1 else ''}", block, count=1)
        out.append(index_html[last:a] + block)
        last = b
    return "".join(out) + index_html[last:]


def render_series(slug, owner, manifest):
    entry = owner.get(slug)
    if not entry or len(entry["slugs"]) < 2:
        return ""
    slugs = entry["slugs"]
    i = slugs.index(slug)

    def link(cls, label, target):
        if target is None:
            return f'<span class="{cls} is-empty"></span>'
        title = html.escape(manifest[target]["title"])
        return (f'<a class="{cls}" href="{target}.html"><span>{label}</span>'
                f'<strong>{title}</strong></a>')

    prev_slug = slugs[i - 1] if i > 0 else None
    next_slug = slugs[i + 1] if i + 1 < len(slugs) else None
    return "\n".join([
        SERIES_START,
        '<nav class="series-footer" aria-label="Series navigation">',
        f'  <div class="series-footer-label">Part of <a href="../index.html#{entry["id"]}">'
        f'{html.escape(entry["title"])}</a> · {i + 1} of {len(slugs)}</div>',
        '  <div class="series-footer-links">',
        "    " + link("series-prev", "← Previous", prev_slug),
        "    " + link("series-next", "Next →", next_slug),
        "  </div>",
        "</nav>",
        SERIES_END,
    ])


def replace_series(s, block):
    if SERIES_START in s:
        a, b = s.index(SERIES_START), s.index(SERIES_END) + len(SERIES_END)
        s = (s[:a].rstrip("\n") + "\n" + s[b:].lstrip("\n")) if not block else s[:a] + block + s[b:]
        return s
    if not block:
        return s
    i = s.rindex("</main>")
    return s[:i] + block + "\n" + s[i:]


def broken_links(files):
    ids = {f: set(re.findall(r'id="([^"]+)"', f.read_text(encoding="utf-8"))) for f in files}
    problems = []
    for f in files:
        for href in re.findall(r'(?:href|src)="([^"]+)"', f.read_text(encoding="utf-8")):
            if href.startswith(("http:", "https:", "mailto:", "javascript:", "data:")) or "${" in href:
                continue
            target_path, _, frag = href.partition("#")
            target_path = target_path.split("?")[0]
            target = f if not target_path else (f.parent / target_path).resolve()
            if not target.exists():
                problems.append(f"{f.relative_to(ROOT)}: missing file {href}")
            elif frag and target in ids and frag not in ids[target]:
                problems.append(f"{f.relative_to(ROOT)}: missing anchor {href}")
    return problems


def main():
    check = "--check" in sys.argv
    manifest = {p["slug"]: p for p in json.loads((ROOT / "blog/index.json").read_text())["posts"]}
    nav_template = (ROOT / "partials/nav.html").read_text(encoding="utf-8")
    files = html_files()
    series, series_owner = load_series((ROOT / "index.html").read_text(encoding="utf-8"))

    outputs = {}
    for f in files:
        s = f.read_text(encoding="utf-8")
        s = replace_nav(s, render_nav(nav_template, f), f)
        s = replace_seo(s, render_seo(f, s, manifest))
        if f.name == "index.html" and f.parent == ROOT:
            s = sync_series_counts(s)
        if f.parent.name == "blog" and f.stem in manifest:
            s = replace_series(s, render_series(f.stem, series_owner, manifest))
        outputs[f] = s
    outputs[ROOT / "blog/series.json"] = json.dumps(
        {"generated_by": "scripts/build.py", "series": series}, indent=2, ensure_ascii=False) + "\n"
    outputs[ROOT / "sitemap.xml"] = render_sitemap(files, manifest)
    outputs[ROOT / "robots.txt"] = ROBOTS
    outputs[ROOT / "404.html"] = render_404(nav_template)

    stale = [p for p, s in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != s]
    if check:
        # sitemap lastmod for non-post pages uses today's date, so ignore date-only drift there
        stale = [p for p in stale if p.name != "sitemap.xml"]
        readme = subprocess.run([sys.executable, str(ROOT / "scripts/update_readme.py"), "--check"])
        problems = [f"stale: {p.relative_to(ROOT)} (run python3 scripts/build.py)" for p in stale]
        problems += broken_links(files)
        if readme.returncode:
            problems.append("stale: README.md (run python3 scripts/build.py)")
        for line in problems:
            print(line)
        sys.exit(1 if problems else 0)

    for p in stale:
        p.write_text(outputs[p], encoding="utf-8")
    subprocess.run([sys.executable, str(ROOT / "scripts/update_readme.py")], check=True)
    problems = broken_links(files)
    print(f"build: {len(stale)} file(s) updated, {len(files)} pages checked, {len(problems)} broken link(s)")
    for line in problems:
        print("  " + line)
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
